fix(#1137 #1138): ie11 share modal for add imet to share and modal height and few performance update
Gapminder/dollar-street-pages pull request #1168
Opened 2017-12-06 15:35 UTC by Miffael

2017-12-07 08:59 UTC, dmitryuck approved these changes

2017-12-07 09:37 UTC, korel-san requested changes
update `addPlaceToSet` function for more humanreadable form

2017-12-12 09:13 UTC, korel-san requested changes
move interfaces to a separate file

2017-12-12 10:14 UTC, korel-san approved these changes

2017-12-21 09:34 UTC, merged