fix(heder-filters): fix position in one row on tablet and mobile
Gapminder/dollar-street-pages pull request #827
Opened 2017-06-01 09:04 UTC by mdmitriy

2017-06-01 09:22 UTC, rychkog requested changes

2017-06-01 09:22 UTC, rychkog commented on src/shared/countries-filter/countries-filter.component.ts
> +        this.activeCountries = getTranslatedCountries.slice(0, this.sliceCount).join(', ') + ' (+' + (getTranslatedCountries.length - this.sliceCount) + ')';
Use template strings syntax

2017-06-01 09:22 UTC, rychkog commented on src/shared/countries-filter/countries-filter.component.ts
> +          this.activeCountries = getTranslatedCountries.slice(0, this.sliceCount).join(', ') + ' (+' + (getTranslatedCountries.length - this.sliceCount) + ')';
Use template strings syntax

2017-06-01 09:22 UTC, rychkog commented on src/shared/countries-filter/countries-filter.component.ts
> +        this.activeCountries = getTranslatedCountries.slice(0, this.sliceCount).join(', ') + ' (+' + (getTranslatedCountries.length - this.sliceCount) + ')';
Use template strings syntax

2017-06-01 09:22 UTC, rychkog commented on src/shared/countries-filter/countries-filter.component.ts
> +                                getTranslatedCountries.slice(0, this.sliceCount).join(', ') + ' (+' + (activeCountriesNum - this.sliceCount) + ')';
Use template strings syntax

2017-06-01 09:22 UTC, rychkog commented on src/shared/countries-filter/countries-filter.component.ts
> +      this.activeCountries = concatLocations.slice(0, this.sliceCount).join(', ') + ' (+' + (concatLocations.length - this.sliceCount) + ')';
Use template strings syntax

2017-06-01 09:22 UTC, rychkog commented on src/shared/header/header.component.ts
> +  public resizeSubscribe: Subscription;
resizeSubscription

2017-06-01 09:22 UTC, rychkog commented on src/shared/header/header.component.ts
> +  public resizeSubscribe: Subscription;
orientationChangeSubscription

2017-06-01 09:22 UTC, rychkog commented on src/shared/header/header.component.ts
> +    this.incomeContainer = this.element.querySelector('.income-title-container') as HTMLElement;
Could you get rid of this query selector and use @ViewChild?

2017-06-01 09:22 UTC, rychkog commented on src/shared/header/header.component.ts
> +        this.zone.run(() => {
Are you sure you need a zone here?

2017-06-01 12:43 UTC, mdmitriy commented on src/shared/header/header.component.ts
> +    this.incomeContainer = this.element.querySelector('.income-title-container') as HTMLElement;
We have a hole section in performance iteration to replace querySelectors with ViewChild let do this during it

2017-06-02 09:52 UTC, rychkog requested changes

2017-06-02 09:52 UTC, rychkog commented on .config/tools/bstack-local.js
> +// const bsConfig = require(path.dirname(confDir)+'/bs-config.json');
Why is it here? If it is not needed anymore - should be removed

2017-06-02 09:52 UTC, rychkog commented on .config/tools/bstack-local.js
> +const PORT = process.env.PORT; //|| bsConfig.port;
same as above

2017-06-02 09:52 UTC, rychkog commented on src/shared/countries-filter/countries-filter.component.ts
> +  @Output('isFilterGotData')
you don't need to specify name of the output if it is the same as field name

2017-06-02 09:52 UTC, rychkog commented on src/shared/countries-filter/countries-filter.component.ts
> +  public selectedFilter: EventEmitter<any> = new EventEmitter<any>();
any ?

2017-06-02 12:54 UTC, merged